services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - APPOPTIONS__DbConnectionString=Host=db;Port=5432;Database=testdb;Username=testuser;Password=testpass
      - APPOPTIONS__JwtSecret=dfKDL0Rq26AEQhdHBcQkOvMNjj9S8/thdKhTVzm3UDWXfJ0gePCuWyf48VK9/hk1ID4VHqZjXpYhinms1r+Khg==
    depends_on:
      - db
      - mqtt-broker
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mqtt-broker:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    command: |
      sh -c '
      echo "listener 1883 0.0.0.0
      allow_anonymous true" > /mosquitto/config/mosquitto.conf && 
      mosquitto -c /mosquitto/config/mosquitto.conf'
volumes:
  postgres_data:

