services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    environment:
      - APPOPTIONS__DbConnectionString=Host=db;Port=5432;Database=testdb;Username=testuser;Password=testpass
      - APPOPTIONS__JwtSecret=dfKDL0Rq26AEQhdHBcQkOvMNjj9S8/thdKhTVzm3UDWXfJ0gePCuWyf48VK9/hk1ID4VHqZjXpYhinms1r+Khg==
      - APPOPTIONS__ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - db
      - mqtt-broker
  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
      - POSTGRES_DB=testdb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mqtt-broker:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
volumes:
  postgres_data:

