version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  default:
    driver: bridge