name: API tests with .NET + TestContainers

on:
  workflow_dispatch:
  push:


jobs:
  local_development:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8'
      - uses: docker/setup-buildx-action@v3
      - run: dotnet test server/Api.Tests/Api.Tests.csproj
        timeout-minutes: 10