name: Update README

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug repository state
        run: |
          pwd
          ls -la
          echo "Current git status:"
          git status

      - name: Setup script
        run: |
          chmod +x ./update-readme-snippets.sh
          echo "Script contents:"
          cat ./update-readme-snippets.sh

      - name: Run update script
        run: |
          ./update-readme-snippets.sh
          echo "Git status after script:"
          git status
          echo "README.md contents:"
          cat README.md

      - name: Commit changes if any
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet README.md; then
            echo "Changes detected in README.md"
            git add README.md
            git commit -m "Update README.md with latest file snippets"
            git push
          else
            echo "No changes to commit"
          fi