name: Update README

on:
  push:
    branches:
      - master
  workflow_dispatch: 

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update README
        run: bash ./update-readme-snippets.sh

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"
          git add README.md
          git commit -m "Update README.md" || exit 0
          git push