name: Update README

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug directory contents
        run: |
          pwd
          ls -la
          cat README.md

      - name: Make script executable
        run: |
          chmod +x ./update-readme-snippets.sh
          ls -la ./update-readme-snippets.sh

      - name: Update README
        run: |
          ./update-readme-snippets.sh
          echo "Content after update:"
          cat README.md

      - name: Check git status
        run: |
          git status
          git diff README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git diff --cached --quiet || (git commit -m "Update README.md with latest file snippets" && git push)

      - name: Final verification
        run: |
          echo "Final README.md content:"
          cat README.md
          echo "Git status after push:"
          git status